version: '3.8'

services:
  # 1. Banco de Dados (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: agro_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: agro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d agro_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Message Broker (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: agro_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Protocolo AMQP
      - "15672:15672" # Management UI
    networks:
      - agro-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Observabilidade - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: agro_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - agro-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # 4. Observabilidade - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: agro_grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - agro-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards

  identity-service:
    build:
      context: .
      dockerfile: src/AGRO.Identity.Service/Dockerfile
    container_name: agro_identity
    environment:
      - CAST_YOUR_VOTE=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=agro_identity_db;Username=admin;Password=adminpassword
      - Jwt__Key=segredo_super_secreto_para_o_hackathon
      - Jwt__Issuer=AgroSolutions
      - Jwt__Audience=AgroSolutions
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:8080"
    networks:
      - agro-network

  management-service:
    build:
      context: .
      dockerfile: src/AGRO.Management.Service/Dockerfile
    container_name: agro_management
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=agro_management_db;Username=admin;Password=adminpassword
    depends_on:
      postgres:
        condition: service_healthy
      identity-service:
        condition: service_started
    ports:
      - "5002:8080"
    networks:
      - agro-network

  ingestion-service:
    build:
      context: .
      dockerfile: src/AGRO.Ingestion.Service/Dockerfile
    container_name: agro_ingestion
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5003:8080"
    networks:
      - agro-network

  alert-service:
    build:
      context: .
      dockerfile: src/AGRO.Alert.Service/Dockerfile
    container_name: agro_alert
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=agro_alert_db;Username=admin;Password=adminpassword
      - RabbitMq__HostName=rabbitmq
      - RabbitMq__UserName=guest
      - RabbitMq__Password=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - agro-network

volumes:
  postgres_data:
  grafana_data:

networks:
  agro-network:
    driver: bridge
