global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'identity_service'
    scrape_interval: 5s
    static_configs:
      - targets: ['identity-service:8080'] 

  - job_name: 'management_service'
    scrape_interval: 5s
    static_configs:
      - targets: ['management-service:8080']

  - job_name: 'ingestion_service'
    scrape_interval: 5s
    static_configs:
      - targets: ['ingestion-service:8080']

  - job_name: 'alert_service'
    scrape_interval: 5s
    static_configs:
      - targets: ['alert-service:8080']
