apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-grafana
  template:
    metadata:
      labels:
        app: agro-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: agro-secrets
                  key: GF_SECURITY_ADMIN_USER
                  optional: true
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agro-secrets
                  key: GF_SECURITY_ADMIN_PASSWORD
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-json
              mountPath: /etc/grafana/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources-cm
        - name: grafana-dashboards-provider
          configMap:
            name: grafana-dashboards-provider-cm
        - name: grafana-dashboards-json
          configMap:
            name: grafana-dashboards-json-cm
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  type: NodePort
  selector:
    app: agro-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
