apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-postgres
  template:
    metadata:
      labels:
        app: agro-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "adminpassword"
            - name: POSTGRES_DB
              value: "agro_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-initdb
          configMap:
            name: postgres-initdb-cm
---
apiVersion: v1
kind: Service
metadata:
  name: agro-postgres
  namespace: default
spec:
  selector:
    app: agro-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-cm
  namespace: default
data:
  01-create-databases.sql: |
    -- Bancos criados apenas na primeira inicialização (quando o volume está vazio)
    CREATE DATABASE agro_identity_db;
    CREATE DATABASE agro_management_db;
    CREATE DATABASE agro_alert_db;
