apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-alert
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-alert
  template:
    metadata:
      labels:
        app: agro-alert
    spec:
      containers:
        - name: alert
          image: agro-alert:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=agro-postgres;Port=5432;Database=agro_alert_db;Username=admin;Password=adminpassword"
            - name: RabbitMq__HostName
              value: "rabbitmq"
            - name: RabbitMq__UserName
              value: "guest"
            - name: RabbitMq__Password
              value: "guest"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agro-alert
  namespace: default
spec:
  selector:
    app: agro-alert
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
