apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-identity
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-identity
  template:
    metadata:
      labels:
        app: agro-identity
    spec:
      containers:
        - name: identity
          image: agro-identity:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=agro-postgres;Port=5432;Database=agro_identity_db;Username=admin;Password=adminpassword"
            - name: JwtSettings__SecretKey
              value: "super_secret_key_for_hackathon_agro_solutions_2026"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agro-identity
  namespace: default
spec:
  type: NodePort
  selector:
    app: agro-identity
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
