apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-ingestion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-ingestion
  template:
    metadata:
      labels:
        app: agro-ingestion
    spec:
      containers:
        - name: ingestion
          image: agro-ingestion:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: RabbitMQ__HostName
              value: "rabbitmq"
            - name: RabbitMQ__UserName
              value: "guest"
            - name: RabbitMQ__Password
              value: "guest"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agro-ingestion
  namespace: default
spec:
  type: NodePort
  selector:
    app: agro-ingestion
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
