apiVersion: apps/v1
kind: Deployment
metadata:
  name: agro-management
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agro-management
  template:
    metadata:
      labels:
        app: agro-management
    spec:
      containers:
        - name: management
          image: agro-management:latest
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: agro-secrets
                  key: CONNECTION_STRING_MANAGEMENT
            - name: JwtSettings__SecretKey
              valueFrom:
                secretKeyRef:
                  name: agro-secrets
                  key: JWT_SECRET_KEY
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agro-management
  namespace: default
spec:
  type: NodePort
  selector:
    app: agro-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
